### ISSUE TITLE
有swift3之后的吗?

### ISSUE THREAD

**Issue by shaoting0730** [yagamis/emmitParticles#1]
我把源码拷贝进Xcode8.2.1显示好多错误

**Comment by yagamis** [comment]
即将更新

**Comment by shaoting0730** [comment]
这个文件需要依赖其他库吗?我可以打开你的那个直播项目,烟花效果文件也没有报错.但是为何我的项目不行呢?

**Comment by shaoting0730** [comment]
好了,好像是Xcode的问题,今天我再来一次就好了.谢谢.你这个动画和爱心动画很赞
